### ISSUE TITLE
C headers don't have C++ extern wrapper

### ISSUE THREAD

**Issue by BrianSipos** [NASA-AMMOS/anms-camp#2]
C headers should include an "extern" wrapper between their own includes and the end include guard. Without these the header is unusable with a C++ compilation unit.

For example:

```
#include "..."

#ifdef __cplusplus
extern "C" {
#endif

...

#ifdef __cplusplus
}
#endif

#endif /* GUARD_H */
```

**Comment by Pulkit1822** [comment]
I can help
